### ISSUE TITLE
Racket implementation

### ISSUE THREAD

**Issue by mirohs** [7guis/7guis#10]
From 7guis created by [soegaard](https://github.com/soegaard): eugenkiss/7guis#40  

Note that Felleisen has implemented the tasks here:

https://github.com/mfelleisen/7GUI

**Comment by spdegabrielle** [comment]
this has been added to

https://github.com/7guis/7guis/blob/master/site/src/containers/Implementations.js#L350

https://github.com/7guis/7guis/blob/7d260aee0ff065de00193e63953cd71f6f8c4e19/site/src/containers/Implementations.js#L350


Sadly the site requires a rebuild and I'm not set up to do that.

**Comment by tbreuss** [comment]
This has been released right now, see: https://7guis.github.io/7guis/implementations

FYI: The publish script has to be run locally. This is kind of "special" but works so far.
