### ISSUE TITLE
Joined

### ISSUE THREAD

**Issue by spdegabrielle** [7guis/7guis#17]
@dumblob 
> @mirohs @tbreuss @spdegabrielle I've just created https://github.com/7guis organization and invited you all. Please accept the invitation to become a member and I'll promote you all to "owner" (you can't be an owner without becoming a member).
> 

I've joined. Please mark me as an owner.

**Comment by dumblob** [comment]
Done @spdegabrielle and welcome! Thanks for your contributions so far.

There is still a lot to do...
