### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by LifeIsStrange** [7guis/7guis#19]
https://eugenkiss.com/projects/thesis.pdf
https://7guis.github.io/7guis/more#:~:text=your%20link%20here%3A-,Comparison%20of%20Object%2DOriented%20and%20Functional%20Programming%20for%20GUI,-Development

**Comment by tbreuss** [comment]
This should be fixed now, see pdf links at https://7guis.github.io/7guis/more

**Comment by LifeIsStrange** [comment]
Thanks :)
